### PR TITLE
#165309827 add user voting page

### PR DESCRIPTION
**Pull request by Niyitangasam**
#### What does this PR do?
- This is for adding a voting page to the user dashboard

#### Description of Task to be completed?

-  Create a page where a user can view all candidates and vote one per office.

-  Add option of scrolling in case the candidates can not fit on one interface.

#### How should this be manually tested? 

- N/A

#### Any background context you want to provide?

- N/A

#### What are the relevant pivotal tracker stories?

-  The story ID is [#165309827](https://www.pivotaltracker.com/n/projects/2325346/stories/165309827)

#### Screenshots (if appropriate)

image

### CODE REVIEW

**Comment by Kabalisa** [comment]
nice @Niyitangasam. what I can suggest is to put color on the vote buttons.

**Comment by Niyitangasam** [comment]
@Kabalisa, I am justing putting colour when the cursor hovers over the vote buttons. I don't know if you are justing me in that way or if I will have to give those buttons different colours.

**Comment by Kabalisa** [comment]
@Niyitangasam I think you can give them a different colour. that ways they have a different colour with their background. they are both white hence the buttons are somehow not visible.

**Comment by Niyitangasam** [comment]
@Kabalisa, I have changed the vote buttons background colour. You can check again if there is anything else to rectify.

**Pull request merged**
